name: inspect-tag-in-hub
description: An action to scan a helm repo for docker tags and check if they exist in a hub
inputs:
  hub-username:
    description: The username to use for the hub
    required: true
  hub-password:
    description: The password to use for the hub
    required: true
  target-path:
    description: The path to the helm repo to scan
    default: .
  github-token:
    description: The token to use for github
    required: true
runs:
  using: node20
  main: check_image_tag.js
  post: comment.js